a. Crear una lista con los siguientes elementos

In [1]:
import numpy as np
import pandas as pd

In [2]:
l=[3,6,9,5,6,7,8,11,5]


In [3]:
arrnp1 = np.array(l)

In [4]:
arrnp1

array([ 3,  6,  9,  5,  6,  7,  8, 11,  5])

b. Obtener el valor máximo, el mínimo y el valor medio del array redondeado a 2 decimales

In [11]:
vmax = arrnp1.max() 
vmin = arrnp1.min()
vmed = arrnp1.mean()
round(vmax,2), round(vmin,2),round(vmed,2)

(11, 3, 6.67)

c) Crear un segundo array numpy (arrnp2) y realizar las siguientes operaciones

In [12]:
l2=[5,6,3,5,7,9,4,10,3]
arrnp2= np.array(l2)
arrnp2

array([ 5,  6,  3,  5,  7,  9,  4, 10,  3])

➢ Sumar elemento a elemento arrnp1 con arrnp2
➢ Concatenar arrnp1 con arrnp2
➢ Añadir un elemento (20) al array resultante del paso anterior
➢ Crear un nuevo array partiendo el array anterior con los elementos mayores que 5
➢ Escribir a fichero el array resultado del paso anterior

In [16]:
#Sumar
suma1 = arrnp1 + arrnp2
suma1

array([ 8, 12, 12, 10, 13, 16, 12, 21,  8])

In [15]:
#Concatenar
arrnp_conca = np.concatenate([arrnp1, arrnp2])
arrnp_conca

In [22]:
arrnp_conca=np.append(arrnp_conca,20)
arrnp_conca

array([ 3,  6,  9,  5,  6,  7,  8, 11,  5,  5,  6,  3,  5,  7,  9,  4, 10,
        3, 20, 20])

In [29]:
mayor_5=arrnp_conca[arrnp_conca>5]
mayor_5

array([ 6,  9,  6,  7,  8, 11,  6,  7,  9, 10, 20, 20])